tShirtApp.controller('tShirtCtrl',['$scope',function($scope){
	$scope.tShirts =  [
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""},
		{location:"/images/1.jpg",description:"lorem ipsum",price:""},
		{location:"/images/2.jpg",description:"lorem ipsum",price:""},
		{location:"/images/3.jpg",description:"lorem ipsum",price:""}
	];
	$scope.searchInput = "";

}])